### ISSUE TITLE
A Responsive Form

### ISSUE THREAD

**Issue by riasenpai** [Coders-Evoke-Community/Amazing-Frontend_Templates#10]
**Is your feature request related to a problem? Please describe.**
I would like to work on a responsive login form.

**Additional context**
I would like to make this form and this issue is open to comments @Ayan-thecodeking

**Comment by riasenpai** [comment]
@Ayan-thecodeking I would like to work on this under Hacktoberfest.

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking I would like to work on this under Hacktoberfest.

yup sure @riasenpai ...firstly make a pr assign for assigned issue
