### ISSUE TITLE
Food Website Footer

### ISSUE THREAD

**Issue by MananAgr2003** [Coders-Evoke-Community/Amazing-Frontend_Templates#123]
The Footer Of The Food Website Looks Very Basic And It Can be Updated To Make It Look Better.

I Would Like To Design And Implement A New Footer For The Food Website.

**Comment by its-harsshhh** [comment]
i would like to work on this issue. kindly assign it to me

**Comment by Ayan-thecodeking** [comment]
hey @MananAgr2003 pls add both the ss of the footer before and after ... to know what changes are you doing.
and you're ready to go

**Comment by MananAgr2003** [comment]
BEFORE :

![prevFooter](https://user-images.githubusercontent.com/92633110/193418549-2264cb8e-b05e-458e-a125-b15d6f1c5234.png)
 
AFTER:

![newFoot](https://user-images.githubusercontent.com/92633110/193418567-131893b4-ba65-4a8e-b6c8-cc4228067257.png)

**Comment by Ishukumarpathak** [comment]
Please assign me the issue. I want to work on that.
