### ISSUE TITLE
weather app template

### ISSUE THREAD

**Issue by Tushar-2003** [Coders-Evoke-Community/Amazing-Frontend_Templates#124]
**Is your feature request related to a problem? Please describe.**
template for a simple weather app.

**Describe the solution you'd like**
I want to add a template for a simple weather app.

**Describe alternatives you've considered**
if someone else has already added this then it is great.
**Additional context**
it would be helpful if my pr is accepted

**Comment by Ayan-thecodeking** [comment]
@Tushar-2003 hey dude when you have created this template ?? if you had done it before 1 Oct then it might not be considered according to hacktorfest rules and regulations. pls make sure you're adding recent projects

**Comment by Tushar-2003** [comment]
I have added it after 1st October. It is showing in my hacktoberfest profile.
