### ISSUE TITLE
'My pets website Template

### ISSUE THREAD

**Issue by its-harsshhh** [Coders-Evoke-Community/Amazing-Frontend_Templates#131]
<h1>I would like to contribute a 'My pets website' template more like a minimalist template.</h1>

**Comment by its-harsshhh** [comment]
I have created a PR. kindly reviewed it :)
https://github.com/Coders-Evoke-Community/Amazing-Frontend_Templates/pull/129

**Comment by its-harsshhh** [comment]
@Ayan-thecodeking

**Comment by Ayan-thecodeking** [comment]
Hey @its-harsshhh it's not valid if you request a PR before asking to assign , next time please keep it in mind

**Comment by its-harsshhh** [comment]
@Ayan-thecodeking pardon!! i forget to create an issue. kindly accept this time. next time, i keep this in my mind
