### ISSUE TITLE
Responsive FAQ template

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Coders-Evoke-Community/Amazing-Frontend_Templates#134]
**Is your feature request related to a problem? Please describe.**
Yes. I will be adding FAQ template which can be beginner friendly and responsive.

**Describe the solution you'd like**
This project will be build using Html,Css,Javascript.

**Describe alternatives you've considered**

NA

**Additional context**

**Comment by Ayan-thecodeking** [comment]
sure @Sulagna-Dutta-Roy pls go ahead also add one clip while making a PR
