### ISSUE TITLE
Add a Sneaker Website

### ISSUE THREAD

**Issue by Adit0507** [Coders-Evoke-Community/Amazing-Frontend_Templates#135]
**Is your feature request related to a problem? Please describe.**
I want to add a really cool sneakers ecommerce site made with HTML, CSS and JavaScript. 

**Describe the solution you'd like**
Checkout the live site here:  https://adit0507.github.io/Sneaker-Site/

**Comment by Ayan-thecodeking** [comment]
hey @Adit0507 let me know when you have created this site ??

**Comment by Adit0507** [comment]
> I made this on 18th Feb, u can check the repo here: https://github.com/Adit0507/Sneaker-Site

*uploaded

**Comment by Adit0507** [comment]
@Ayan-thecodeking Is it good to go ?

**Comment by Adit0507** [comment]
@Ayan-thecodeking Should I proceed ? If so kindly assign it to me.

**Comment by Ayan-thecodeking** [comment]
@Adit0507 go ahead
