### ISSUE TITLE
Weather WebApp Template

### ISSUE THREAD

**Issue by sshiwangi** [Coders-Evoke-Community/Amazing-Frontend_Templates#144]
**Is your feature request related to a problem? Please describe.**
I would like to add a weather webapp template.

**Describe the solution you'd like**
The website will be built using html and css and will be responsive.

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by sshiwangi** [comment]
@Ayan-thecodeking please assign me this issue under hacktoberfest.

**Comment by Ayan-thecodeking** [comment]
@sshiwangi go ahead
