### ISSUE TITLE
Tour Before Trip

### ISSUE THREAD

**Issue by Asttttha** [Coders-Evoke-Community/Amazing-Frontend_Templates#151]
Html, Css and JS project, with background video.

![Screenshot (284)](https://user-images.githubusercontent.com/95849912/194314597-03273d4c-574a-4281-a73d-5a947f14f604.png)

![Screenshot (283)](https://user-images.githubusercontent.com/95849912/194314499-0d18becf-56c3-4f70-9b9e-1fbf9733a731.png)

please assign this issue.

**Comment by Ayan-thecodeking** [comment]
@Asttttha .. make a PR with deployed link
