### ISSUE TITLE
Add a Blog Website

### ISSUE THREAD

**Issue by sshiwangi** [Coders-Evoke-Community/Amazing-Frontend_Templates#158]
**Is your feature request related to a problem? Please describe.**
I would like to add a blog website.

**Describe the solution you'd like**
It will be responsive and built using HTML, CSS and JavaScript.

**Describe alternatives you've considered**

**Additional context**

**Comment by sshiwangi** [comment]
@Ayan-thecodeking please assign me this issue under hacktoberfest.

**Comment by Ayan-thecodeking** [comment]
sure @sshiwangi make a PR with deployed link
