### ISSUE TITLE
Add a 3D product page for Nike Air Jordan.

### ISSUE THREAD

**Issue by zaidsidd360** [Coders-Evoke-Community/Amazing-Frontend_Templates#161]
**Is your feature request related to a problem? Please describe.**
I want to add a 3D product page for Nike Air Jordan shoes. Kindly assign me this issue under the Hacktoberfest label.

**Describe the solution you'd like**
The page will have the product visible in 3D and users can rotate and view the shoes from every angle.

**Describe alternatives you've considered**
NA

**Additional context**
*Screenshots* 

![cart](https://user-images.githubusercontent.com/87397035/194832316-4ae432a8-42e5-4ed6-a296-ddd4f7004737.png)
![green](https://user-images.githubusercontent.com/87397035/194832331-151b3725-2f4b-4974-920e-19b7034b34bc.png)
![red](https://user-images.githubusercontent.com/87397035/194832343-90fd8085-f4a6-4089-8a6c-e31d1f1e16cb.png)
![redsmall](https://user-images.githubusercontent.com/87397035/194832353-f14f596c-e9aa-4419-8fed-db9bc5e179a0.png)

**Comment by Ayan-thecodeking** [comment]
great @zaidsidd360 move ahead

**Comment by zaidsidd360** [comment]
Hey @Ayan-thecodeking , it's a react app and so far I've seen people contributing basic html, css and js code. Should I still go ahead and make the pr?

**Comment by darshitdudhaiya** [comment]
hey @Ayan-thecodeking  i have code for it but where will i put it in repo?
