### ISSUE TITLE
Linktree template

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [Coders-Evoke-Community/Amazing-Frontend_Templates#163]
**Is your feature request related to a problem? Please describe.**
I will be creating linktree template using html,css,js.

**Describe the solution you'd like**
It will be fully responsive as well

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Ayan-thecodeking** [comment]
sure @Sulagna-Dutta-Roy
