### ISSUE TITLE
About,gallery and contact sections in the navbar aren't working

### ISSUE THREAD

**Issue by Antara25-10** [Coders-Evoke-Community/Amazing-Frontend_Templates#19]
I would like to fix this issue

**Comment by Aditya-619** [comment]
hey @Antara25-10  I had already made a contact form, if you wanna fix this issue you can continue with the about and gallery sections.

**Comment by Antara25-10** [comment]
Alright..but I don't think that contact form is connected with the navbar..and I want to fix that

**Comment by Ayan-thecodeking** [comment]
hey @Antara25-10 for now we are not looking for that pages you can work on other issues
