### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by nandini7637** [Coders-Evoke-Community/Amazing-Frontend_Templates#20]
@Ayan-thecodeking can I build a template for about us page?

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking can I build a template for about us page?

ya sure @nandini7637  but don't add it on website ...just make it for templates

**Comment by swaraj-ssk** [comment]
I want to add about page. Can you please tell me in what format you want it ?
