### ISSUE TITLE
Project Title Improvement

### ISSUE THREAD

**Issue by Garima-7** [Coders-Evoke-Community/Amazing-Frontend_Templates#24]
**Describe the bug**
Project Title is not visible in some cards.

**Corrected behavior**
Adding background color to Project Title so that it is clearly visible.

**Screenshots**

![Screenshot (449)](https://user-images.githubusercontent.com/83363645/135609745-e4d23d2f-b35e-42b7-9350-05fe96fc7ce1.png)
![Screenshot (450)](https://user-images.githubusercontent.com/83363645/135609768-60827961-646f-4427-825d-0a7b957de64e.png)

**Comment by Garima-7** [comment]
Please assign me this issue.

**Comment by Ayan-thecodeking** [comment]
hey this is already improved ...pls look our for another issue 
focus on templates @Garima-7
