### ISSUE TITLE
Improvement in the flex box used.

### ISSUE THREAD

**Issue by Antlia360** [Coders-Evoke-Community/Amazing-Frontend_Templates#25]
**Is your feature request related to a problem? Please describe.**
The image box used looks sticky.

**Describe the solution you'd like**
Adding some transition, hover effects would make it look good.

**Comment by Antlia360** [comment]
@Ayan-thecodeking can you assign this work to me?

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking can you assign this work to me?

Hey @Antlia360 someone is working already ....we have this project project for templates ...read readme and start add templates
