### ISSUE TITLE
Footer for the Website

### ISSUE THREAD

**Issue by pranshukas** [Coders-Evoke-Community/Amazing-Frontend_Templates#4]
<hr>

## Description 📜

I would like to work on footer. I want to add this feature. Please suggest me the design/things to be added in the footer part. I am keen to work on this. 
Please assign me this task. 

<hr>

## Domain of Contribution 📊
- [x] Footer

## Any tutorials or Documentation are you going to add 

<hr>

**Comment by pranshukas** [comment]
Hello, @Ayan-thecodeking I would like to work on Footer. Please assign me this issue. Also, please suggest me the design of the footer and things that are to be added in the footer. I am keen to work on this.

**Comment by Prajakta102** [comment]
Please assign this task to me as I have good understanding of HTML , CSS JavaScript .
Also this is my first open source contribution.

**Comment by Ayan-thecodeking** [comment]
> Hello, @Ayan-thecodeking I would like to work on Footer. Please assign me this issue. Also, please suggest to me the design of the footer and things that are to be added in the footer. I am keen to work on this. I have good experience in Frontend (HTML, CSS/Bootstrap, Javascript/Jquery). I am new to Open Source and really
![design figma](https://user-images.githubusercontent.com/78692566/135608366-196c6fe8-7b94-42f7-a1d8-b62dc319350d.png)
 keen to learn and contribute

sure go ahead @pranshukas make according to this

**Comment by Ayan-thecodeking** [comment]
> Please assign this task to me as I have good understanding of HTML , CSS JavaScript . Also this is my first open source contribution.
search out any other issues 
@Prajakta102

**Comment by SoundaryaKhanapur** [comment]
Can I work on this ?
