### ISSUE TITLE
Adding greet bot in repo 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/Amazing-Frontend_Templates#42]

**Comment by utkarsh1311** [comment]
Is there any way I can help?

**Comment by sanskaromar** [comment]
Describe the issue pls

**Comment by swaraj-ssk** [comment]
I am willing to contribute to this. Can you assign me this one ?

**Comment by pranshukas** [comment]
@Ayan-thecodeking I think this might Help ! 
https://medium.datadriveninvestor.com/welcome-first-time-contributors-to-your-github-repo-with-welcome-bot-93474758ac7e

In case you want I can help with this !

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking I think this might Help ! https://medium.datadriveninvestor.com/welcome-first-time-contributors-to-your-github-repo-with-welcome-bot-93474758ac7e
> 
> In case you want I can help with this !

Thnx @pranshukas
