### ISSUE TITLE
Add a FAQ template

### ISSUE THREAD

**Issue by TishaJhabak1014** [Coders-Evoke-Community/Amazing-Frontend_Templates#57]
**Is your feature request related to a problem? Please describe.**
This addition will help web apps grab the code for the faq section and customize it.

**Describe the solution you'd like**
I will use HTML, CSS, JS, Bootstrap to implement this

**Describe alternatives you've considered**
I will try to add a dark mode feature too.

**Additional context**

**Comment by TishaJhabak1014** [comment]
@Ayan-thecodeking issue created, plz add the labels. and assign me.

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking issue created, plz add the labels. and assign me.

Ook @TishaJhabak1014
