### ISSUE TITLE
add Responsiveness in website 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Coders-Evoke-Community/Amazing-Frontend_Templates#6]

**Comment by gunjan-g** [comment]
@Ayan-thecodeking can I work on this issue

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking can I work on this issue

Sure go ahead :)

**Comment by gunjan-g** [comment]
> > @Ayan-thecodeking can I work on this issue
> 
> Sure go ahead :)

please assign me this issue

**Comment by jigarvyasidea** [comment]
I would like to work on this

**Comment by Ayan-thecodeking** [comment]
ya sure @jigarvyasidea go ahead 
just add responsiveness in full website

**Comment by prathameshpatil2002** [comment]
to which website we have to add responsivness ?

**Comment by AbhishekTiwari23** [comment]
I want to work on it. If possible, then please assign
