### ISSUE TITLE
Add a Fitness Template 

### ISSUE THREAD

**Issue by Subhradeep10** [Coders-Evoke-Community/Amazing-Frontend_Templates#7]
I want to add a template, inside the projects

**Comment by Ayan-thecodeking** [comment]
hey @Subhradeep10 ...go ahead but before that explain in brief about ur template

**Comment by TishaJhabak1014** [comment]
@Ayan-thecodeking can I also add a faq template? Plz let me know.

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking can I also add a faq template? Plz let me know.

Create an another issue

**Comment by TishaJhabak1014** [comment]
> > @Ayan-thecodeking can I also add a faq template? Plz let me know.
> 
> Create an another issue

sure. Thank you.
