### ISSUE TITLE
A Responsive Card that could be multi purpose

### ISSUE THREAD

**Issue by riasenpai** [Coders-Evoke-Community/Amazing-Frontend_Templates#9]
**Is your feature request related to a problem? Please describe.**
A responsive Profile card or a simple card with some animation where an image and some kind of description can be included.

**Describe the solution you'd like**
Making this card functionality with some animations.

**Additional context**
This issue is open to suggestions from @Ayan-thecodeking or other admins.

**Comment by riasenpai** [comment]
@Ayan-thecodeking I would like to work on this.

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking I would like to work on this under Hacktoberfest.

sure @riasenpai go ahead
